### ISSUE TITLE
Pen is not working while daemon is running.

### ISSUE THREAD

**Issue by Maximumtix** [kurikaesu/userspace-tablet-driver-daemon#10]
Xp-Pen Deco 01 V2
Tablet entry is removed from `xsetwacom list` and stylus stops working when daemon is run. `sudo libinput record --show-keycodes` stills shows xp pen and xp pen pad but doesn't respond to events. I have carried your config files. Stopping the daemon and replugging fixes the stylus.

**Comment by kurikaesu** [comment]
Resolved over IRC. Thanks again for helping me debug the issues.
