### ISSUE TITLE
Right dial on XP-Pen Artist 22R Pro is clone of left dial

### ISSUE THREAD

**Issue by jbigler** [kurikaesu/userspace-tablet-driver-daemon#22]
The right dial on my XP-Pen Artist 22R Pro is doing the same actions that are assigned to the left dial. 
I installed the GUI as well and edited the mappings, but the right dial always performs whatever actions are assigned to the left dial.

**Comment by kurikaesu** [comment]
Thanks for the bug report. I can confirm the problem happens on my side too. Will have a fix out shortly and will rebuild the 0.1.3 debian file.
