### ISSUE TITLE
Add a dependency to libusb-1.0-0 to CMakeLists.txt

### ISSUE THREAD

**Issue by allo-** [kurikaesu/userspace-tablet-driver-daemon#34]
cmake doesn't check for libusb headers when configuring the project.

**Comment by kurikaesu** [comment]
Thanks for the report, are you able to make the change and send a PR?

**Comment by allo-** [comment]
Maybe after I actually get my tablet running. I am a bit struggling since the official tool stopped working and really hope your project helps.

It looks like libusb can be added as cmake package: https://fossies.org/linux/xbmc/cmake/modules/FindLibUSB.cmake
