### ISSUE TITLE
"Could not get descriptor" error

### ISSUE THREAD

**Issue by jbigler** [kurikaesu/userspace-tablet-driver-daemon#38]
Beginning with the ad0e0cff7ced753f93481f429bb42541dfcd5464 commit I am no longer able to use the driver. 
This is with an XP-Pen 22R Pro.

```
Listening on socket /home/xxx/.local/var/run/userspace_tablet_driver_daemon.sock
xp_pen_handler initialized
huion_handler initialized
Handling XP-Pen Artist 22R Pro
Setup completed on interface 0
Setup completed on interface 1
Could not get descriptor
Could not claim device on attempt 0. Detaching and then waiting
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 1. Detaching and then waiting
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 2. Detaching and then waiting
```

The error is caused by the descriptorLength variable being hard coded to 13 when the code to attach the devices was consolidated in src/xp_pen_unified_device.cpp. In the case of the 22R Pro and some other tablets it should be 12. If the length is meaningful, it may have to be assigned as a device level variable instead of defining it in the function.

**Comment by kurikaesu** [comment]
Thanks for the report. I no longer have the 22r Pro in my possession so I wasn't able to test this on the device. I'll rework this to allow for the lengths to be variable as you suggested!
