### ISSUE TITLE
Running on wayland

### ISSUE THREAD

**Issue by albfan** [kurikaesu/userspace-tablet-driver-daemon#46]
Hi

I just see comments on README about wayland. I'm using it:

```
echo $XDG_SESSION_TYPE 
wayland
```

After review what daemon this installs:

```
$ sudo make install
[sudo] password for alberto: 
[100%] Built target userspace_tablet_driver_daemon
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/bin/userspace_tablet_driver_daemon
-- Up-to-date: /etc
-- Up-to-date: /etc/udev
-- Up-to-date: /etc/udev/rules.d
-- Up-to-date: /etc/udev/rules.d/70-huion.rules
-- Up-to-date: /etc/udev/rules.d/70-xp-pen.rules
-- Up-to-date: /etc/udev/rules.d/70-uinput-plugdev.rules
-- Up-to-date: /usr
-- Up-to-date: /usr/share
-- Up-to-date: /usr/share/X11
-- Up-to-date: /usr/share/X11/xorg.conf.d
-- Up-to-date: /usr/share/X11/xorg.conf.d/60-xp-pen.conf
-- Up-to-date: /usr/share/X11/xorg.conf.d/60-huion.conf
```

it just writes to: `~/.local/var/run/userspace_tablet_driver_daemon.sock`

I started it:

$ userspace_tablet_driver_daemon 
Listening on socket /home/alberto/.local/var/run/userspace_tablet_driver_daemon.sock
No existing config so we will be creating a new one
xp_pen_handler initialized
huion_handler initialized
Handling Huion tablet
Got firmware HUION_T200_210309
Resolved device name to Huion KD100 mini Keydial
Attached to interface 0
Setup completed on interface 0
Setup completed on interface 1
Setup completed on interface 2
Set up config for device 512: (Unknown Huion device)

and it was able to read my config (Huion KD100):

![Captura de pantalla de 2022-01-25 14-25-23](https://user-images.githubusercontent.com/220968/150985147-435f1ec7-ad0a-4221-a1b6-2fe28a77e90a.png)

![Captura de pantalla de 2022-01-25 14-25-27](https://user-images.githubusercontent.com/220968/150985181-04a5eaa6-edd6-4fd4-9d52-b2a800236dea.png)

And modify keys.

So there's only lack of how to expose those keys in wayland (because yes, it only outputs garbage)

**Comment by albfan** [comment]
It's suppose the using libei, or a tool that uses lbei: https://gitlab.freedesktop.org/libinput/libei/

something like uinput would also work, but it's lower level

@kurikaesu any tips of where to implement this? I'm tempted to detect wayland using "XDG_SESSION_TYPE" env var and use this library to send keys

**Comment by kurikaesu** [comment]
Interesting. I've tested my tablets under wayland and the express/shortcut keys appear to work correctly. Granted, I have not done this anytime recently. I wonder if it is because the KD100 is not being identified as a keyboard device. With xorg/X11 the configuration files force the device to be handled by libinput.

**Comment by albfan** [comment]
I own a HS611 and default customization provided by GNOME mostly works (it just miss some side bar keys and upper scroll)

![image](https://user-images.githubusercontent.com/220968/151077444-12758131-400a-4827-8b9f-5bb4473a00dd.png)

for KD100 

![image](https://user-images.githubusercontent.com/220968/151077532-f5a1128b-fe1e-4c8a-b60c-505425bd03e4.png)

looks it behaves as no driver mode when just connected, 

https://support.huion.com/en/support/solutions/articles/44002245976-huion-mini-keydial-kd100-faqs

although it doesn't match for me. It exposes: 
k1 Ctrl+Z 
k2 Ctrl+Shift+Z
k5 Ctrl+Space
k6 F5

rest of keys and dial are empty.

I need to clear any setup I made `rm ~/.local/share/userspace_tablet_driver_daemon/driver.cfg` or no key works for me.

I understand from lsusb:

    Bus 001 Device 005: ID 256c:006d

I need to rework something on `src/huion_handler.cpp` but not sure where 


and using your userspace server it outputs

**Comment by albfan** [comment]
hmm looks like it is behaving as keystrokes for GNOME tablet:

![Captura de pantalla de 2022-01-26 01-24-18](https://user-images.githubusercontent.com/220968/151082277-039b3ced-fa08-4edd-a37d-52e29111498b.png)

it only exposes 8 keys, while this device has 16 square buttons + two large buttons + dial + 1 mouse button

still your userspace server + wayland looks interesting to implement to me

**Comment by albfan** [comment]
Finally my approach was to expose how you detect real device through wireless usb dongle (firmware) here:

https://github.com/linuxwacom/libwacom/issues/469

I think expose device through a common library api allows to deal with devices easily.

what do you think? Still able to collaborate here to add wayland support if you need. Reopen if you want to see it implemented
