### ISSUE TITLE
XP-Pen 22E Pro interface claim issue

### ISSUE THREAD

**Issue by Silmathoron** [kurikaesu/userspace-tablet-driver-daemon#48]
I hit some unexpected trouble with the 22E Pro driver that used to work my PR.
After reinstalling Pop OS and the driver, I get for ``userspace_tablet_driver_daemon``:

```shell
Listening on socket ~/.local/var/run/userspace_tablet_driver_daemon.sock
xp_pen_handler initialized
huion_handler initialized
Handling XP-Pen Artist 22E Pro
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 0. Detaching and then waiting
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 1. Detaching and then waiting
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 2. Detaching and then waiting
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 3. Detaching and then waiting
Could not claim interface 0 retcode: -6 errno: 16
Could not claim device on attempt 4. Detaching and then waiting
Giving up
```

I don't think it's a problem with the driver because the official XP-Pen driver also fails to recognize the device... any idea what could be going wrong? Maybe some missing dependencies?

udev and xorg rules have properly been added.

**Comment by kurikaesu** [comment]
An error number of 16 indicates the device is busy which generally means another application or driver has claimed the device and isn't letting it go.

**Comment by Silmathoron** [comment]
OK, thanks, I uninstalled the XP-Pen driver and there is some progress but not full recovery... now I get:

```shell
Listening on socket ~/.local/var/run/userspace_tablet_driver_daemon.sock
xp_pen_handler initialized
huion_handler initialized
Handling XP-Pen Artist 22E Pro
Setup completed on interface 0
Setup completed on interface 1
Could not create uinput pen
Could not create uinput pad
Attached to interface 2
Sending init key on endpont 3
Setup completed on interface 2
Set up config for device 2315
```

So the pen is not responsive, probably because ``xsetwacom list devices`` returns no devices... any idea why this might be?

Btw: the xp-pen driver was not causing any issue with your code previously, did anything change recently?

**Comment by Silmathoron** [comment]
Btw, just saw that you now provide deb files so tried with it, same output...
Also the GUI lists "Unknown device 1 0429:2315" instead of the proper name (and does not load any configuration). There *might* be a space between the 1 and the 0 of 10429

**Comment by kurikaesu** [comment]
I've checked the commit history and nothing was introduced recently. That "could not create uinput pen" and pad leads me to believe that your OS does not give your user the "plugdev" user group? The udev rules only gives "plugdev" access as that is what happens on my Ubuntu system.

The GUI may be missing your device as a configurable device. I'll go check and add it in if that is the case.

**Comment by kurikaesu** [comment]
I had not updated the GUI debian packages in a while so if you installed that then it would not have had your device config.
I've published a new version here that is up to date: https://github.com/kurikaesu/userspace-tablet-driver-gui/releases/tag/v0.1.2
