### ISSUE TITLE
After install..

### ISSUE THREAD

**Issue by AdsonCicilioti** [kurikaesu/userspace-tablet-driver-daemon#53]
I'm on Arch Linux. I have a HUION HS611. I installed AUR.

After installation, do I need to do anything?
Start some service?

**Comment by kurikaesu** [comment]
Once installed, run the driver in a terminal window by executing: 
```
userspace_tablet_driver_daemon
```

It should start spitting out a bunch of information and detect your device though I don't have a Huion HS611 to work out the firmware name which means it will likely spit out the firmware name but then say the device is unknown.

If you can provide the firmware name it gives in the terminal, I can add it to this driver

**Comment by kurikaesu** [comment]
Closing this as I haven't received any responses.
