### ISSUE TITLE
Why are there new releases every hour?

### ISSUE THREAD

**Issue by ThatOneCalculator** [kurikaesu/userspace-tablet-driver-daemon#63]
I think you might've misconfigured an action or something, but your nightly release announces a new tag every hour.

**Comment by kurikaesu** [comment]
Weird. Thanks for letting me know. I'll disable the nightly build. It was supposed to be a build every night but the amount of code changes being made now means that doesn't make much sense.

**Comment by kurikaesu** [comment]
I've made the change to the Circle CI config to stop it from building nightlies.
